export const syncTables = [
    {
        tableName: "Category",
        primaryKey: "category_id",
        bulkEndpoint: "/api/categories/bulk",
        updatedSinceEndpoint: "/api/categories/updated-since",
        lastSyncKey: "categories_last_sync",
        payloadKey: "categories",
    },
    {
        tableName: "Product",
        primaryKey: "product_id",
        bulkEndpoint: "/api/products/bulk",
        updatedSinceEndpoint: "/api/products/updated-since",
        lastSyncKey: "products_last_sync",
        payloadKey: "products",
    },

    {
        tableName: "Sale",
        primaryKey: "sale_id",
        bulkEndpoint: "/api/sales/bulk",
        updatedSinceEndpoint: "/api/sales/updated-since",
        lastSyncKey: "sales_last_sync",
        payloadKey: "sales",
    },
    {
        tableName: "SaleItems",
        primaryKey: "sale_item_id",
        bulkEndpoint: "/api/sales-items/bulk",
        updatedSinceEndpoint: "/api/sales-items/updated-since",
        lastSyncKey: "sales_item_last_sync",
        payloadKey: "sales",
    },
    {
        tableName: "CashRegister",
        primaryKey: "register_id",
        bulkEndpoint: "/api/cash-registrations/bulk",
        updatedSinceEndpoint: "/api/cash-registrations/updated-since",
        lastSyncKey: "cash-registrations_last_sync",
        payloadKey: "registrations",
    },
    {
        tableName: "Refunds",
        primaryKey: "refund_id",
        bulkEndpoint: "/api/refunds/bulk",
        updatedSinceEndpoint: "/api/refunds/updated-since",
        lastSyncKey: "refunds_last_sync",
        payloadKey: "refunds",
    },
    {
        tableName: "RefundItems",
        primaryKey: "refund_item_id",
        bulkEndpoint: "/api/refund-items/bulk",
        updatedSinceEndpoint: "/api/refund-items/updated-since",
        lastSyncKey: "refund_items_last_sync",
        payloadKey: "refunds",
    },
    {
        tableName: "Inventory_log",
        primaryKey: "inventory_log_id",
        bulkEndpoint: "/api/inventory-logs/bulk",
        updatedSinceEndpoint: "/api/inventory-logs/updated-since",
        lastSyncKey: "inventory_log_last_sync",
        payloadKey: "inventories",
    },
    {
        tableName: "User",
        primaryKey: "user_id",
        bulkEndpoint: "/api/auth/bulk",
        updatedSinceEndpoint: "/api/auth/updated-since",
        lastSyncKey: "auth_last_sync",
        payloadKey: "auth",
    },
];